[18.0] [FIX] stock_batch_picking.py: remove line updating `self.carrier_code`
This line has been added by https://github.com/OCA/delivery-carrier/commit/3b0232dae3aa5073d69e18b593675a8bdd557ad9 but it looks like the field carrier_code has never been added to the model (or at least it has never been merged in the OCA repo?), thus we get following error when updating the ``carrier_id``:
```
[...]
  File "/odoo/src/addons/web/models/models.py", line 1005, in onchange
    record._apply_onchange_methods(field_name, result)
  File "/odoo/src/odoo/models.py", line 7364, in _apply_onchange_methods
    res = method(self)
          ^^^^^^^^^^^^
  File "/odoo/external-src/delivery-carrier/delivery_carrier_label_batch/models/stock_batch_picking.py", line 61, in onchange_carrier_id
    self.carrier_code = self.carrier_id.code
    ^^^^^^^^^^^^^^^^^
AttributeError: 'stock.picking.batch' object has no attribute 'carrier_code'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://localhost:8069/web/assets/e5ed061/web.assets_web.min.js:3144:163)
        at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/e5ed061/web.assets_web.min.js:3149:13)
```